#!/bin/bash

echo "============================================================================================================"
echo " Test3: Use two libraries."
echo "============================================================================================================"
rm -rf testout3
../bin/SRAssembler -q input/LOC_Os06g04560.pep -p SRAssembler.conf -l libraries_200bp_1kb.conf -r ./processed_reads -x 15000 -o testout3

echo "============================================================================================================"
echo " Test4: Previous example, but using the MPI implementation."
echo "============================================================================================================"
rm -rf testout4
mpirun -n 4 ../bin/SRAssembler_MPI -q input/LOC_Os06g04560.pep -p SRAssembler.conf -l libraries_200bp_1kb.conf -r ./processed_reads -o testout4
