#!/bin/bash

echo "============================================================================================================"
echo " Test1: Use the -1, -2 options to assign reads files."
echo "============================================================================================================"
rm -rf testout1
rm -rf processed_reads
../bin/SRAssembler -q input/LOC_Os06g04560.pep -p SRAssembler.conf -1 input/reads1_200.fq -2 input/reads2_200.fq -z 200 -r ./processed_reads -x 15000 -o testout1

echo "============================================================================================================"
echo " Test2: Use the MPI implementation, read library specifications from conf file (only the second, new"
echo "        library will be pre-processed)."
echo "============================================================================================================"
rm -rf testout2
mpirun -n 4 ../bin/SRAssembler_MPI -q input/LOC_Os06g04560.pep -p SRAssembler.conf -l libraries_200bp_1kb.conf -r ./processed_reads -x 15000 -o testout2
